name=AODV
version=1.0.0
author=Igor Levkov <levkov.igor@gmail.com>
maintainer=Igor Levkov <levkov.igor@gmail.com>
sentence=AODV routing library precompiled for ESP32 and STM32 GenF4.
paragraph=A high-performance precompiled implementation of the AODV routing protocol for mesh networking.
category=Communication
url=https://github.com/levkovigor/AODV
architectures=*
precompiled=true
ldflags=-lAODV
